[project]
name = "car3"
type = "node"

[deploy]
startCommand = "npm start"
healthCheckPath = "/"
healthCheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[env]
NODE_VERSION = "22"
PUPPETEER_SKIP_CHROMIUM_DOWNLOAD = "true" 